Updated ProduceResources to use ProduceResource
RobinStephenson/jbt-3 pull request #27
Opened 2017-03-01 20:09 UTC by tc975

closes #12

2017-03-02 12:19 UTC, RobinStephenson requested changes

2017-03-02 12:19 UTC, RobinStephenson commented on core/src/io/github/teamfractal/entity/LandPlot.java
> +        produced[0] = produceResource(ResourceType.ORE);
Would be more maintainable if we kept this in a loop

2017-03-03 12:13 UTC, RobinStephenson commented on core/src/io/github/teamfractal/entity/LandPlot.java
> +        produced[0] = produceResource(ResourceType.ORE);
Also needs a comment saying changed by JBT and that we did it to make it more maintainable

2017-03-03 12:51 UTC, tc975 commented on core/src/io/github/teamfractal/entity/LandPlot.java
> +        produced[0] = produceResource(ResourceType.ORE);
added the comment, but I don't see a way of changing it to a loop. ProdceResource takes a resourceType and I see no way of selecting an indicidual type in a loop.

2017-03-03 13:12 UTC, RobinStephenson approved these changes

2017-03-03 13:16 UTC, merged